
platform :ios, '9.0'

target 'ReactNativeSkelton' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
  ], :inhibit_warnings => true
  pod 'yoga',             :path => '../node_modules/react-native/ReactCommon/yoga',
                          :inhibit_warnings => true
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec',
                          :inhibit_warnings => true
  pod 'glog',  :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec',
               :inhibit_warnings => true
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec',
               :inhibit_warnings => true

  target 'ReactNativeSkeltonTests' do
    inherit! :search_paths
  end

  script_phase :name => 'StartPackager',
               :script => 'sh ../scripts/launchPackager.sh'

  plugin 'cocoapods-fix-react-native'
end
